# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Production dependencies - triggers semantic releases
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"  # Triggers PATCH release
    open-pull-requests-limit: 10
    ignore:
      # Ignore test dependencies in this update group
      - dependency-name: "io.mockk:*"
      - dependency-name: "org.junit.jupiter:*"
      - dependency-name: "org.pitest:*"
      - dependency-name: "org.jeasy:*"
      - dependency-name: "org.hamcrest:*"
      - dependency-name: "org.apache.commons:commons-lang3"
    groups:
      lsd-dependencies:
        patterns:
          - "io.github.lsd-consulting:*"
        update-types:
          - "minor"
          - "patch"

      spring-dependencies:
        patterns:
          - "org.springframework.*:*"
          - "org.springframework.cloud:*"
          - "io.pivotal.spring.cloud:*"
        update-types:
          - "minor"
          - "patch"

      json-dependencies:
        patterns:
          - "com.google.code.gson:*"
          - "com.fasterxml.jackson.*:*"
        update-types:
          - "minor"
          - "patch"

      utility-dependencies:
        patterns:
          - "com.j2html:*"
        update-types:
          - "minor"
          - "patch"

      kotlin-dependencies:
        patterns:
          - "org.jetbrains.kotlin*"
        update-types:
          - "minor"
          - "patch"

  # Test dependencies - does not trigger semantic releases
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "test"  # Does not trigger semantic release
    open-pull-requests-limit: 5
    groups:
      testing-dependencies:
        patterns:
          - "io.mockk:*"
          - "org.junit.jupiter:*"
          - "org.pitest:*"
          - "org.jeasy:*"
          - "org.hamcrest:*"
          - "org.apache.commons:commons-lang3"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"  # For workflow updates - no version impact
