dependencies {

    // LSD
    api 'io.github.lsd-consulting:lsd-core:9.0.0'
    api 'io.github.lsd-consulting:lsd-distributed-connector:3.0.0'
    implementation 'io.github.lsd-consulting:lsd-formatting-library:6.0.0'
    compileOnly 'io.github.lsd-consulting:lsd-distributed-mongodb-connector:9.0.0'
    compileOnly 'io.github.lsd-consulting:lsd-distributed-postgres-connector:6.0.0'
    compileOnly 'io.github.lsd-consulting:lsd-distributed-http-connector:8.0.0'

    // Spring
    compileOnly 'org.springframework.boot:spring-boot-starter'

    // Other
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.22'
    implementation 'com.j2html:j2html:1.6.0'
}
